spring:
  application:
    name: diplom
  jpa:
    database:     postgresql
    generate-ddl: false
    show-sql:     true
  datasource:
    driver-class-name: org.postgresql.Driver
    url:               jdbc:postgresql://localhost:5432/diplom
    username:          nearbygems
    password:          123
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled:    true
    drop-first: false

logging:
  level:
    org:
      springframework:
        orm:
          jpa:
            JpaTransactionManager=DEBUG: