version: "3"

services:

  postgres:
    image:          postgres:12.0
    container_name: postgres
    restart:        always
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
      - ./postgres-init:/docker-entrypoint-initdb.d

  zookeeper:
    image:          wurstmeister/zookeeper
    container_name: zookeeper
    restart:        always
    ports:
      - "2181:2181"

  kafka:
    image:          wurstmeister/kafka
    container_name: kafka
    restart:        always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT:              zookeeper:2181
      KAFKA_LISTENERS:                      DOCKER://:9091,HOST://:9092
      KAFKA_ADVERTISED_LISTENERS:           DOCKER://kafka:9091,HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER:PLAINTEXT,HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME:     DOCKER

  kafdrop:
    image:          obsidiandynamics/kafdrop:3.28.0-SNAPSHOT
    container_name: kafdrop
    depends_on:
      - kafka
    restart:        always
    ports:
      - "19000:9000"                                              # KAFDROP   http://localhost:9000
    environment:
      KAFKA_BROKERCONNECT:        "kafka:9091"
      SERVER_PORT:                "9000"
      JVM_OPTS:                   "-Xms32M -Xmx164M"
      SERVER_SERVLET_CONTEXTPATH: "/"

#  prometheus:
#    image:          prom/prometheus:v2.35.0
#    network_mode:   host
#    container_name: prometheus
#    restart:        unless-stopped
#    ports:
#      - '9090:9090'
#    volumes:
#      - ./prometheus:/etc/prometheus
#      - prometheus-data:/prometheus
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yaml'
#
#  grafana:
#    image:          grafana/grafana-oss:8.5.2
#    network_mode:   host
#    container_name: grafana
#    restart:        unless-stopped
#    volumes:
#      - ./data/grafana:/var/lib/grafana
#    environment:
#      - GF_SECURITY_ADMIN_PASSWORD=admin
#      - GF_SERVER_DOMAIN=localhost
#    ports:
#      - "3000:3000"